pg:
  jdbc-url: jdbc:postgresql:///postgres
  username: demo
  password: demo
  instance-name: solid-alignment-272000:europe-west1:demo-johann

mail:
  from: johann.reboulleau@gmail.com
  personalFrom: Johann

redis:
  host: 10.208.249.83
  port: 6379