pg:
  jdbc-url: jdbc:postgresql:///postgres
  username: postgres
  password: postgres
  instance-name: poc-demo-johann-asia-south1:asia-south1:sql-pg-demo-johann

mail:
  from: johann.reboulleau@gmail.com
  personalFrom: Johann

redis:
  host: 10.55.85.179
  port: 6379
spring:
  redis:
    host: 10.55.85.179
    port: 6379